#Generación de data frame para cada abeja con columnas de interes y listado general de plantas#

library(tidyr)
library(EDAWR)
library(dplyr)
library(tidyverse)
library(purrr)

#Cargar nombres"
nombres <-read.csv("Clave.csv",header=T)

#Cargar todas las especies"
AGAANG <-read.csv("1.csv", header=TRUE)
AGAFEM <-read.csv("2.csv", header=TRUE)
AGAOBL <-read.csv("3.csv", header=TRUE)
AGASPL <-read.csv("4.csv", header=TRUE)
AGATEX <-read.csv("5.csv", header=TRUE)
AGAVIR <-read.csv("6.csv", header=TRUE)
ANDARC <-read.csv("7.csv", header=TRUE)
ANDCAN <-read.csv("8.csv", header=TRUE)
ANDCAR <-read.csv("9.csv", header=TRUE)
ANDCER <-read.csv("10.csv", header=TRUE)
ANDMAN <-read.csv("11.csv", header=TRUE)
ANDMIS <-read.csv("12.csv", header=TRUE)
ANDNAS <-read.csv("13.csv", header=TRUE)
ANDNUB <-read.csv("14.csv", header=TRUE)
ANDPRU <-read.csv("15.csv", header=TRUE)
ANTBOM <-read.csv("16.csv", header=TRUE)
ANTEDW <-read.csv("17.csv", header=TRUE)
ANTMAC <-read.csv("18.csv", header=TRUE)
ANTMOR <-read.csv("19.csv", header=TRUE)
ANTNOT <-read.csv("20.csv", header=TRUE)
ANTOCC <-read.csv("21.csv", header=TRUE)
ANTPRT <-read.csv("22.csv", header=TRUE)
ANTROB <-read.csv("23.csv", header=TRUE)
ANTSQU <-read.csv("24.csv", header=TRUE)
ANTTEN <-read.csv("25.csv", header=TRUE)
ANTURB <-read.csv("26.csv", header=TRUE)
ANTURS <-read.csv("27.csv", header=TRUE)
ANTUTA <-read.csv("28.csv", header=TRUE)
ASHBUC <-read.csv("29.csv", header=TRUE)
ASHCAC <-read.csv("30.csv", header=TRUE)
ASHCAL <-read.csv("31.csv", header=TRUE)
ATOCOP <-read.csv("32.csv", header=TRUE)
AUCAUR <-read.csv("33.csv", header=TRUE)
AUGMET <-read.csv("34.csv", header=TRUE)
AUGPUR <-read.csv("35.csv", header=TRUE)
BOMCAL <-read.csv("36.csv", header=TRUE)
BOMFER <-read.csv("37.csv", header=TRUE)
BOMGRI <-read.csv("38.csv", header=TRUE)
BOMHUN <-read.csv("39.csv", header=TRUE)
BOMIMP <-read.csv("40.csv", header=TRUE)
BOMINS <-read.csv("41.csv", header=TRUE)
BOMMIX <-read.csv("42.csv", header=TRUE)
BOMMLP <-read.csv("43.csv", header=TRUE)
BOMNEV <-read.csv("44.csv", header=TRUE)
BOMPEN <-read.csv("45.csv", header=TRUE)
BOMRUF <-read.csv("46.csv", header=TRUE)
BOMSON <-read.csv("47.csv", header=TRUE)
BOMSUC <-read.csv("48.csv", header=TRUE)
BOMVOS <-read.csv("49.csv", header=TRUE)
CALAND <-read.csv("50.csv", header=TRUE)
CERACA <-read.csv("51.csv", header=TRUE)
CERNAN <-read.csv("52.csv", header=TRUE)
CERNAU <-read.csv("53.csv", header=TRUE)
CERNEO <-read.csv("54.csv", header=TRUE)
COEOCT <-read.csv("55.csv", header=TRUE)
COEPOR <-read.csv("56.csv", header=TRUE)
COERUF <-read.csv("57.csv", header=TRUE)
COESAY <-read.csv("58.csv", header=TRUE)
COESOD <-read.csv("59.csv", header=TRUE)
COLCOM <-read.csv("60.csv", header=TRUE)
COLKIN <-read.csv("61.csv", header=TRUE)
COLLTZ <-read.csv("62.csv", header=TRUE)
COLSIM <-read.csv("63.csv", header=TRUE)
COLSLE <-read.csv("64.csv", header=TRUE)
COLSPH <-read.csv("65.csv", header=TRUE)
DIAAUS <-read.csv("66.csv", header=TRUE)
DIACUR <-read.csv("67.csv", header=TRUE)
DIADIM <-read.csv("68.csv", header=TRUE)
DIAPUD <-read.csv("69.csv", header=TRUE)
DIARIN <-read.csv("70.csv", header=TRUE)
DIASUB <-read.csv("71.csv", header=TRUE)
EPEBIF <-read.csv("72.csv", header=TRUE)
EPECOM <-read.csv("73.csv", header=TRUE)
EPEMIN <-read.csv("74.csv", header=TRUE)
EPEPUS <-read.csv("75.csv", header=TRUE)
EPESCU <-read.csv("76.csv", header=TRUE)
EUCEDW <-read.csv("77.csv", header=TRUE)
HABCIN <-read.csv("78.csv", header=TRUE)
HALFAR <-read.csv("79.csv", header=TRUE)
HALLIG <-read.csv("80.csv", header=TRUE)
HALTRI <-read.csv("81.csv", header=TRUE)
HERCAR <-read.csv("82.csv", header=TRUE)
HERVAR <-read.csv("83.csv", header=TRUE)
HOLCAL <-read.csv("84.csv", header=TRUE)
HOPALB <-read.csv("85.csv", header=TRUE)
HOPFUL <-read.csv("86.csv", header=TRUE)
HOPGRI <-read.csv("87.csv", header=TRUE)
HOPPRO <-read.csv("88.csv", header=TRUE)
HYLMES <-read.csv("89.csv", header=TRUE)
HYLMOD <-read.csv("90.csv", header=TRUE)
HYLWOO <-read.csv("91.csv", header=TRUE)
LASEGR <-read.csv("92.csv", header=TRUE)
LASELI <-read.csv("93.csv", header=TRUE)
LASHDS <-read.csv("94.csv", header=TRUE)
LASICP <-read.csv("95.csv", header=TRUE)
LASIMI <-read.csv("96.csv", header=TRUE)
LASLSR <-read.csv("97.csv", header=TRUE)
LASOBZ <-read.csv("98.csv", header=TRUE)
LASOCC <-read.csv("99.csv", header=TRUE)
LASPCT <-read.csv("100.csv", header=TRUE)
LASPEC <-read.csv("101.csv", header=TRUE)
LASPEX <-read.csv("102.csv", header=TRUE)
LASPRN <-read.csv("103.csv", header=TRUE)
LASRUI <-read.csv("104.csv", header=TRUE)
LASSCL <-read.csv("105.csv", header=TRUE)
LASSIS <-read.csv("106.csv", header=TRUE)
LASTGU <-read.csv("107.csv", header=TRUE)
MEGANG <-read.csv("108.csv", header=TRUE)
MEGAPI <-read.csv("109.csv", header=TRUE)
MEGBRV <-read.csv("110.csv", header=TRUE)
MEGCOQ <-read.csv("111.csv", header=TRUE)
MEGFID <-read.csv("112.csv", header=TRUE)
MEGINI <-read.csv("113.csv", header=TRUE)
MEGLIP <-read.csv("114.csv", header=TRUE)
MEGMEN <-read.csv("115.csv", header=TRUE)
MEGMTV <-read.csv("116.csv", header=TRUE)
MEGONO <-read.csv("117.csv", header=TRUE)
MEGPAR <-read.csv("118.csv", header=TRUE)
MEGPHT <-read.csv("119.csv", header=TRUE)
MEGPOL <-read.csv("120.csv", header=TRUE)
MEGPRU <-read.csv("121.csv", header=TRUE)
MEGPUG <-read.csv("122.csv", header=TRUE)
MEGROT <-read.csv("123.csv", header=TRUE)
MEGSBN <-read.csv("124.csv", header=TRUE)
MEGTXN <-read.csv("125.csv", header=TRUE)
MELAGI <-read.csv("126.csv", header=TRUE)
MELBIM <-read.csv("127.csv", header=TRUE)
MELBIW <-read.csv("128.csv", header=TRUE)
MELCMN <-read.csv("129.csv", header=TRUE)
MELCON <-read.csv("130.csv", header=TRUE)
MELDRU <-read.csv("131.csv", header=TRUE)
MELLUP <-read.csv("132.csv", header=TRUE)
MELMEN <-read.csv("133.csv", header=TRUE)
MELPAL <-read.csv("134.csv", header=TRUE)
MELRIV <-read.csv("135.csv", header=TRUE)
MELSUB <-read.csv("136.csv", header=TRUE)
MELTND <-read.csv("137.csv", header=TRUE)
MELVER <-read.csv("138.csv", header=TRUE)
NOMTEX <-read.csv("139.csv", header=TRUE)
OSMALO <-read.csv("140.csv", header=TRUE)
OSMCAL <-read.csv("141.csv", header=TRUE)
OSMCLL <-read.csv("142.csv", header=TRUE)
OSMCOL <-read.csv("143.csv", header=TRUE)
OSMDEN <-read.csv("144.csv", header=TRUE)
OSMGEO <-read.csv("145.csv", header=TRUE)
OSMLIG <-read.csv("146.csv", header=TRUE)
OSMPUM <-read.csv("147.csv", header=TRUE)
OSMRAR <-read.csv("148.csv", header=TRUE)
OSMTEX <-read.csv("149.csv", header=TRUE)
PEPPRU <-read.csv("150.csv", header=TRUE)
PERALB <-read.csv("151.csv", header=TRUE)
PROGRS <-read.csv("152.csv", header=TRUE)
PSEAET <-read.csv("153.csv", header=TRUE)
PSEALB <-read.csv("154.csv", header=TRUE)
SPHHER <-read.csv("155.csv", header=TRUE)
STEMON <-read.csv("156.csv", header=TRUE)
TRIHEL <-read.csv("157.csv", header=TRUE)
TRILUN <-read.csv("158.csv", header=TRUE)
TRIREM <-read.csv("159.csv", header=TRUE)
XERCAL <-read.csv("160.csv", header=TRUE)
XERCAZ <-read.csv("161.csv", header=TRUE)
XYLVAR <-read.csv("162.csv", header=TRUE)
TRIFUL <-read.csv("TRIFUL.csv", header=TRUE)

lista <- list(AGAANG, AGAFEM, AGAOBL, AGASPL, AGATEX, AGAVIR, ANDARC, ANDCAN, ANDCAR, ANDCER, ANDMAN, ANDMIS, ANDNAS, ANDNUB, ANDPRU, ANTBOM, ANTEDW, ANTMAC, ANTMOR, ANTNOT, ANTOCC, ANTPRT, ANTROB, ANTSQU, ANTTEN, ANTURB, ANTURS, ANTUTA, ASHBUC, ASHCAC, ASHCAL, ATOCOP, AUCAUR, AUGMET, AUGPUR, BOMCAL, BOMFER, BOMGRI, BOMHUN, BOMIMP, BOMINS, BOMMIX, BOMMLP, BOMNEV, BOMPEN, BOMRUF, BOMSON, BOMSUC, BOMVOS, CALAND, CERACA, CERNAN, CERNAU, CERNEO, COEOCT, COEPOR, COERUF, COESAY, COESOD, COLCOM, COLKIN, COLLTZ, COLSIM, COLSLE, COLSPH, DIAAUS, DIACUR, DIADIM, DIAPUD, DIARIN, DIASUB, EPEBIF, EPECOM, EPEMIN, EPEPUS, EPESCU, EUCEDW, HABCIN, HALFAR, HALLIG, HALTRI, HERCAR, HERVAR, HOLCAL, HOPALB, HOPFUL, HOPGRI, HOPPRO, HYLMES, HYLMOD, HYLWOO, LASEGR, LASELI, LASHDS, LASICP, LASIMI, LASLSR, LASOBZ, LASOCC, LASPCT, LASPEC, LASPEX, LASPRN, LASRUI, LASSCL, LASSIS, LASTGU, MEGANG, MEGAPI, MEGBRV, MEGCOQ, MEGFID, MEGINI, MEGLIP, MEGMEN, MEGMTV, MEGONO, MEGPAR, MEGPHT, MEGPOL, MEGPRU, MEGPUG, MEGROT, MEGSBN, MEGTXN, MELAGI, MELBIM, MELBIW, MELCMN, MELCON, MELDRU, MELLUP, MELMEN, MELPAL, MELRIV, MELSUB, MELTND, MELVER, NOMTEX, OSMALO, OSMCAL, OSMCLL, OSMCOL, OSMDEN, OSMGEO, OSMLIG, OSMPUM, OSMRAR, OSMTEX, PEPPRU, PERALB, PROGRS, PSEAET, PSEALB, SPHHER, STEMON, TRIHEL, TRILUN, TRIREM, XERCAL, XERCAZ, XYLVAR)
names(lista) <- nombres$ClaveSp
View(lista)

#Para seleccionar comunas a quedarnos
variables <- c("source_taxon_name", "target_taxon_name", "latitude", "longitude")
result = lapply(lista, "[", , variables)

#Para eliminar duplicados
result2 = lapply(result, distinct)


#Para escribir los listados por especie de abeja
for(i in names(result2)){
  write.csv(result2[[i]], paste0(i,".csv"))
}

#Listado unico de plantas para todas las abejas
Target <- c("target_taxon_name")
Listado = lapply(result2, "[", , Target)
View(Listado)


#Creación de data frame por especie

purrr::iwalk(
  .x = Listado,
  .f = function(x, y) {
    x <- as.data.frame(x)
    y <- paste0('', y)
    assign(y, x, envir = globalenv())
  }
)


#Se retiran las especies sin resultados (BOMSUC, LASPRN, OSMRAR)

Listado_final <-rbind(AGAANG, AGAFEM, AGAOBL, AGASPL, AGATEX, AGAVIR, ANDARC, ANDCAN, ANDCAR, ANDCER, ANDMAN, ANDMIS, ANDNAS, ANDNUB, ANDPRU, ANTBOM, ANTEDW, ANTMAC, ANTMOR, ANTNOT, ANTOCC, ANTPRT, ANTROB, ANTSQU, ANTTEN, ANTURB, ANTURS, ANTUTA, ASHBUC, ASHCAC, ASHCAL, ATOCOP, AUCAUR, AUGMET, AUGPUR, BOMCAL, BOMFER, BOMGRI, BOMHUN, BOMIMP, BOMINS, BOMMIX, BOMMLP, BOMNEV, BOMPEN, BOMRUF, BOMSON, BOMVOS, CALAND, CERACA, CERNAN, CERNAU, CERNEO, COEOCT, COEPOR, COERUF, COESAY, COESOD, COLCOM, COLKIN, COLLTZ, COLSIM, COLSLE, COLSPH, DIAAUS, DIACUR, DIADIM, DIAPUD, DIARIN, DIASUB, EPEBIF, EPECOM, EPEMIN, EPEPUS, EPESCU, EUCEDW, HABCIN, HALFAR, HALLIG, HALTRI, HERCAR, HERVAR, HOLCAL, HOPALB, HOPFUL, HOPGRI, HOPPRO, HYLMES, HYLMOD, HYLWOO, LASEGR, LASELI, LASHDS, LASICP, LASIMI, LASLSR, LASOBZ, LASOCC, LASPCT, LASPEC, LASPEX, LASRUI, LASSCL, LASSIS, LASTGU, MEGANG, MEGAPI, MEGBRV, MEGCOQ, MEGFID, MEGINI, MEGLIP, MEGMEN, MEGMTV, MEGONO, MEGPAR, MEGPHT, MEGPOL, MEGPRU, MEGPUG, MEGROT, MEGSBN, MEGTXN, MELAGI, MELBIM, MELBIW, MELCMN, MELCON, MELDRU, MELLUP, MELMEN, MELPAL, MELRIV, MELSUB, MELTND, MELVER, NOMTEX, OSMALO, OSMCAL, OSMCLL, OSMCOL, OSMDEN, OSMGEO, OSMLIG, OSMPUM, OSMTEX, PEPPRU, PERALB, PROGRS, PSEAET, PSEALB, SPHHER, STEMON, TRIHEL, TRILUN, TRIREM, XERCAL, XERCAZ, XYLVAR)



#Eliminar duplicados
Lista_final <- distinct(Listado_final)

#Guardar archivo
write.csv(Lista_final, "Listado.csv")
