#Script para generar el listado de plantas con paises#

library(tidyr)
library(dplyr)
library(tidyverse)

#Cargar nombres#
nombres <-read.csv("Clave.csv",header=T, fileEncoding = "UTF-8")

#Se cargan las bases, se seleccionan las columnas#
AGAANG <-read.csv("AGAANG.csv", header=TRUE, fileEncoding = "UTF-8"); select(AGAANG, target_taxon_name, NAME_ES)->AGAANG; distinct(AGAANG)->AGAANG; AGAANG$NAME_ES <-replace_na(AGAANG$NAME_ES, "NA")
AGAFEM <-read.csv("AGAFEM.csv", header=TRUE, fileEncoding= "UTF-8"); select(AGAFEM, target_taxon_name, NAME_ES)->AGAFEM; distinct(AGAFEM)->AGAFEM; AGAFEM$NAME_ES <-replace_na(AGAFEM$NAME_ES, "NA")
AGAOBL <-read.csv("AGAOBL.csv", header=TRUE, fileEncoding= "UTF-8"); select(AGAOBL, target_taxon_name, NAME_ES)->AGAOBL; distinct(AGAOBL)->AGAOBL; AGAOBL$NAME_ES <-replace_na(AGAOBL$NAME_ES, "NA")
AGASPL <-read.csv("AGASPL.csv", header=TRUE, fileEncoding= "UTF-8"); select(AGASPL, target_taxon_name, NAME_ES)->AGASPL; distinct(AGASPL)->AGASPL; AGAOBL$NAME_ES <-replace_na(AGAOBL$NAME_ES, "NA")
AGATEX <-read.csv("AGATEX.csv", header=TRUE, fileEncoding= "UTF-8"); select(AGATEX, target_taxon_name, NAME_ES)->AGATEX; distinct(AGATEX)->AGATEX; AGATEX$NAME_ES <-replace_na(AGATEX$NAME_ES, "NA")
AGAVIR <-read.csv("AGAVIR.csv", header=TRUE, fileEncoding= "UTF-8"); select(AGAVIR, target_taxon_name, NAME_ES)->AGAVIR; distinct(AGAVIR)->AGAVIR; AGAVIR$NAME_ES <-replace_na(AGAVIR$NAME_ES, "NA")
ANDARC <-read.csv("ANDARC.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANDARC, target_taxon_name, NAME_ES)->ANDARC; distinct(ANDARC)->ANDARC; ANDARC$NAME_ES <-replace_na(ANDARC$NAME_ES, "NA")
ANDCAN <-read.csv("ANDCAN.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANDCAN, target_taxon_name, NAME_ES)->ANDCAN; distinct(ANDCAN)->ANDCAN; ANDCAN$NAME_ES <-replace_na(ANDCAN$NAME_ES, "NA")
ANDCAR <-read.csv("ANDCAR.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANDCAR, target_taxon_name, NAME_ES)->ANDCAR; distinct(ANDCAR)->ANDCAR; ANDCAR$NAME_ES <-replace_na(ANDCAR$NAME_ES, "NA")
ANDCER <-read.csv("ANDCER.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANDCER, target_taxon_name, NAME_ES)->ANDCER; distinct(ANDCER)->ANDCER; ANDCER$NAME_ES <-replace_na(ANDCER$NAME_ES, "NA")
ANDMAN <-read.csv("ANDMAN.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANDMAN, target_taxon_name, NAME_ES)->ANDMAN; distinct(ANDMAN)->ANDMAN; ANDMAN$NAME_ES <-replace_na(ANDMAN$NAME_ES, "NA")
ANDMIS <-read.csv("ANDMIS.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANDMIS, target_taxon_name, NAME_ES)->ANDMIS; distinct(ANDMIS)->ANDMIS; ANDMIS$NAME_ES <-replace_na(ANDMIS$NAME_ES, "NA")
ANDNAS <-read.csv("ANDNAS.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANDNAS, target_taxon_name, NAME_ES)->ANDNAS; distinct(ANDNAS)->ANDNAS; ANDNAS$NAME_ES <-replace_na(ANDNAS$NAME_ES, "NA")
ANDNUB <-read.csv("ANDNUB.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANDNUB, target_taxon_name, NAME_ES)->ANDNUB; distinct(ANDNUB)->ANDNUB; ANDNUB$NAME_ES <-replace_na(ANDNUB$NAME_ES, "NA")
ANDPRU <-read.csv("ANDPRU.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANDPRU, target_taxon_name, NAME_ES)->ANDPRU; distinct(ANDPRU)->ANDPRU; ANDPRU$NAME_ES <-replace_na(ANDPRU$NAME_ES, "NA")
ANTBOM <-read.csv("ANTBOM.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTBOM, target_taxon_name, NAME_ES)->ANTBOM; distinct(ANTBOM)->ANTBOM; ANTBOM$NAME_ES <-replace_na(ANTBOM$NAME_ES, "NA")
ANTEDW <-read.csv("ANTEDW.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTEDW, target_taxon_name, NAME_ES)->ANTEDW; distinct(ANTEDW)->ANTEDW; ANTEDW$NAME_ES <-replace_na(ANTEDW$NAME_ES, "NA")
ANTMAC <-read.csv("ANTMAC.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTMAC, target_taxon_name, NAME_ES)->ANTMAC; distinct(ANTMAC)->ANTMAC; ANTMAC$NAME_ES <-replace_na(ANTMAC$NAME_ES, "NA")
ANTMOR <-read.csv("ANTMOR.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTMOR, target_taxon_name, NAME_ES)->ANTMOR; distinct(ANTMOR)->ANTMOR; ANTMOR$NAME_ES <-replace_na(ANTMOR$NAME_ES, "NA")
ANTNOT <-read.csv("ANTNOT.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTNOT, target_taxon_name, NAME_ES)->ANTNOT; distinct(ANTNOT)->ANTNOT; ANTNOT$NAME_ES <-replace_na(ANTNOT$NAME_ES, "NA")
ANTOCC <-read.csv("ANTOCC.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTOCC, target_taxon_name, NAME_ES)->ANTOCC; distinct(ANTOCC)->ANTOCC; ANTOCC$NAME_ES <-replace_na(ANTOCC$NAME_ES, "NA")
ANTPRT <-read.csv("ANTPRT.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTPRT, target_taxon_name, NAME_ES)->ANTPRT; distinct(ANTPRT)->ANTPRT; ANTPRT$NAME_ES <-replace_na(ANTPRT$NAME_ES, "NA")
ANTROB <-read.csv("ANTROB.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTROB, target_taxon_name, NAME_ES)->ANTROB; distinct(ANTROB)->ANTROB; ANTROB$NAME_ES <-replace_na(ANTROB$NAME_ES, "NA")
ANTSQU <-read.csv("ANTSQU.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTSQU, target_taxon_name, NAME_ES)->ANTSQU; distinct(ANTSQU)->ANTSQU; ANTSQU$NAME_ES <-replace_na(ANTSQU$NAME_ES, "NA")
ANTTEN <-read.csv("ANTTEN.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTTEN, target_taxon_name, NAME_ES)->ANTTEN; distinct(ANTTEN)->ANTTEN; ANTTEN$NAME_ES <-replace_na(ANTTEN$NAME_ES, "NA")
ANTURB <-read.csv("ANTURB.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTURB, target_taxon_name, NAME_ES)->ANTURB; distinct(ANTURB)->ANTURB; ANTURB$NAME_ES <-replace_na(ANTURB$NAME_ES, "NA")
ANTURS <-read.csv("ANTURS.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTURS, target_taxon_name, NAME_ES)->ANTURS; distinct(ANTURS)->ANTURS; ANTURS$NAME_ES <-replace_na(ANTURS$NAME_ES, "NA")
ANTUTA <-read.csv("ANTUTA.csv", header=TRUE, fileEncoding= "UTF-8"); select(ANTUTA, target_taxon_name, NAME_ES)->ANTUTA; distinct(ANTUTA)->ANTUTA; ANTUTA$NAME_ES <-replace_na(ANTUTA$NAME_ES, "NA")
ASHBUC <-read.csv("ASHBUC.csv", header=TRUE, fileEncoding= "UTF-8"); select(ASHBUC, target_taxon_name, NAME_ES)->ASHBUC; distinct(ASHBUC)->ASHBUC; ASHBUC$NAME_ES <-replace_na(ASHBUC$NAME_ES, "NA")
ASHCAC <-read.csv("ASHCAC.csv", header=TRUE, fileEncoding= "UTF-8"); select(ASHCAC, target_taxon_name, NAME_ES)->ASHCAC; distinct(ASHCAC)->ASHCAC; ASHCAC$NAME_ES <-replace_na(ASHCAC$NAME_ES, "NA")
ASHCAL <-read.csv("ASHCAL.csv", header=TRUE, fileEncoding= "UTF-8"); select(ASHCAL, target_taxon_name, NAME_ES)->ASHCAL; distinct(ASHCAL)->ASHCAL; ASHCAL$NAME_ES <-replace_na(ASHCAL$NAME_ES, "NA")
ATOCOP <-read.csv("ATOCOP.csv", header=TRUE, fileEncoding= "UTF-8"); select(ATOCOP, target_taxon_name, NAME_ES)->ATOCOP; distinct(ATOCOP)->ATOCOP; ATOCOP$NAME_ES <-replace_na(ATOCOP$NAME_ES, "NA")
AUCAUR <-read.csv("AUCAUR.csv", header=TRUE, fileEncoding= "UTF-8"); select(AUCAUR, target_taxon_name, NAME_ES)->AUCAUR; distinct(AUCAUR)->AUCAUR; AUCAUR$NAME_ES <-replace_na(AUCAUR$NAME_ES, "NA")
AUGMET <-read.csv("AUGMET.csv", header=TRUE, fileEncoding= "UTF-8"); select(AUGMET, target_taxon_name, NAME_ES)->AUGMET; distinct(AUGMET)->AUGMET; AUGMET$NAME_ES <-replace_na(AUGMET$NAME_ES, "NA")
AUGPUR <-read.csv("AUGPUR.csv", header=TRUE, fileEncoding= "UTF-8"); select(AUGPUR, target_taxon_name, NAME_ES)->AUGPUR; distinct(AUGPUR)->AUGPUR; AUGPUR$NAME_ES <-replace_na(AUGPUR$NAME_ES, "NA")
BOMCAL <-read.csv("BOMCAL.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMCAL, target_taxon_name, NAME_ES)->BOMCAL; distinct(BOMCAL)->BOMCAL; BOMCAL$NAME_ES <-replace_na(BOMCAL$NAME_ES, "NA")
BOMFER <-read.csv("BOMFER.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMFER, target_taxon_name, NAME_ES)->BOMFER; distinct(BOMFER)->BOMFER; BOMFER$NAME_ES <-replace_na(BOMFER$NAME_ES, "NA")
BOMGRI <-read.csv("BOMGRI.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMGRI, target_taxon_name, NAME_ES)->BOMGRI; distinct(BOMGRI)->BOMGRI; BOMGRI$NAME_ES <-replace_na(BOMGRI$NAME_ES, "NA")
BOMHUN <-read.csv("BOMHUN.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMHUN, target_taxon_name, NAME_ES)->BOMHUN; distinct(BOMHUN)->BOMHUN; BOMHUN$NAME_ES <-replace_na(BOMHUN$NAME_ES, "NA")
BOMIMP <-read.csv("BOMIMP.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMIMP, target_taxon_name, NAME_ES)->BOMIMP; distinct(BOMIMP)->BOMIMP; BOMIMP$NAME_ES <-replace_na(BOMIMP$NAME_ES, "NA")
BOMINS <-read.csv("BOMINS.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMINS, target_taxon_name, NAME_ES)->BOMINS; distinct(BOMINS)->BOMINS; BOMINS$NAME_ES <-replace_na(BOMINS$NAME_ES, "NA")
BOMMIX <-read.csv("BOMMIX.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMMIX, target_taxon_name, NAME_ES)->BOMMIX; distinct(BOMMIX)->BOMMIX; BOMMIX$NAME_ES <-replace_na(BOMMIX$NAME_ES, "NA")
BOMMLP <-read.csv("BOMMLP.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMMLP, target_taxon_name, NAME_ES)->BOMMLP; distinct(BOMMLP)->BOMMLP; BOMMLP$NAME_ES <-replace_na(BOMMLP$NAME_ES, "NA")
BOMNEV <-read.csv("BOMNEV.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMNEV, target_taxon_name, NAME_ES)->BOMNEV; distinct(BOMNEV)->BOMNEV; BOMNEV$NAME_ES <-replace_na(BOMNEV$NAME_ES, "NA")
BOMPEN <-read.csv("BOMPEN.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMPEN, target_taxon_name, NAME_ES)->BOMPEN; distinct(BOMPEN)->BOMPEN; BOMPEN$NAME_ES <-replace_na(BOMPEN$NAME_ES, "NA")
BOMRUF <-read.csv("BOMRUF.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMRUF, target_taxon_name, NAME_ES)->BOMRUF; distinct(BOMRUF)->BOMRUF; BOMRUF$NAME_ES <-replace_na(BOMRUF$NAME_ES, "NA")
BOMSON <-read.csv("BOMSON.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMSON, target_taxon_name, NAME_ES)->BOMSON; distinct(BOMSON)->BOMSON; BOMSON$NAME_ES <-replace_na(BOMSON$NAME_ES, "NA")
#BOMSUC <-read.csv("BOMSUC.csv", header=TRUE, fileEncoding= "UTF-8")
BOMVOS <-read.csv("BOMVOS.csv", header=TRUE, fileEncoding= "UTF-8"); select(BOMVOS, target_taxon_name, NAME_ES)->BOMVOS; distinct(BOMVOS)->BOMVOS; BOMVOS$NAME_ES <-replace_na(BOMVOS$NAME_ES, "NA")
CALAND <-read.csv("CALAND.csv", header=TRUE, fileEncoding= "UTF-8"); select(CALAND, target_taxon_name, NAME_ES)->CALAND; distinct(CALAND)->CALAND; CALAND$NAME_ES <-replace_na(CALAND$NAME_ES, "NA")
CERACA <-read.csv("CERACA.csv", header=TRUE, fileEncoding= "UTF-8"); select(CERACA, target_taxon_name, NAME_ES)->CERACA; distinct(CERACA)->CERACA; CERACA$NAME_ES <-replace_na(CERACA$NAME_ES, "NA")
CERNAN <-read.csv("CERNAN.csv", header=TRUE, fileEncoding= "UTF-8"); select(CERNAN, target_taxon_name, NAME_ES)->CERNAN; distinct(CERNAN)->CERNAN; CERNAN$NAME_ES <-replace_na(CERNAN$NAME_ES, "NA")
CERNAU <-read.csv("CERNAU.csv", header=TRUE, fileEncoding= "UTF-8"); select(CERNAU, target_taxon_name, NAME_ES)->CERNAU; distinct(CERNAU)->CERNAU; CERNAU$NAME_ES <-replace_na(CERNAU$NAME_ES, "NA")
CERNEO <-read.csv("CERNEO.csv", header=TRUE, fileEncoding= "UTF-8"); select(CERNEO, target_taxon_name, NAME_ES)->CERNEO; distinct(CERNEO)->CERNEO; CERNEO$NAME_ES <-replace_na(CERNEO$NAME_ES, "NA")
COEOCT <-read.csv("COEOCT.csv", header=TRUE, fileEncoding= "UTF-8"); select(COEOCT, target_taxon_name, NAME_ES)->COEOCT; distinct(COEOCT)->COEOCT; COEOCT$NAME_ES <-replace_na(COEOCT$NAME_ES, "NA")
COEPOR <-read.csv("COEPOR.csv", header=TRUE, fileEncoding= "UTF-8"); select(COEPOR, target_taxon_name, NAME_ES)->COEPOR; distinct(COEPOR)->COEPOR; COEPOR$NAME_ES <-replace_na(COEPOR$NAME_ES, "NA")
COERUF <-read.csv("COERUF.csv", header=TRUE, fileEncoding= "UTF-8"); select(COERUF, target_taxon_name, NAME_ES)->COERUF; distinct(COERUF)->COERUF; COERUF$NAME_ES <-replace_na(COERUF$NAME_ES, "NA")
COESAY <-read.csv("COESAY.csv", header=TRUE, fileEncoding= "UTF-8"); select(COESAY, target_taxon_name, NAME_ES)->COESAY; distinct(COESAY)->COESAY; COESAY$NAME_ES <-replace_na(COESAY$NAME_ES, "NA")
COESOD <-read.csv("COESOD.csv", header=TRUE, fileEncoding= "UTF-8"); select(COESOD, target_taxon_name, NAME_ES)->COESOD; distinct(COESOD)->COESOD; COESOD$NAME_ES <-replace_na(COESOD$NAME_ES, "NA")
COLCOM <-read.csv("COLCOM.csv", header=TRUE, fileEncoding= "UTF-8"); select(COLCOM, target_taxon_name, NAME_ES)->COLCOM; distinct(COLCOM)->COLCOM; COLCOM$NAME_ES <-replace_na(COLCOM$NAME_ES, "NA")
COLKIN <-read.csv("COLKIN.csv", header=TRUE, fileEncoding= "UTF-8"); select(COLKIN, target_taxon_name, NAME_ES)->COLKIN; distinct(COLKIN)->COLKIN; COLKIN$NAME_ES <-replace_na(COLKIN$NAME_ES, "NA")
COLLTZ <-read.csv("COLLTZ.csv", header=TRUE, fileEncoding= "UTF-8"); select(COLLTZ, target_taxon_name, NAME_ES)->COLLTZ; distinct(COLLTZ)->COLLTZ; COLLTZ$NAME_ES <-replace_na(COLLTZ$NAME_ES, "NA")
COLSIM <-read.csv("COLSIM.csv", header=TRUE, fileEncoding= "UTF-8"); select(COLSIM, target_taxon_name, NAME_ES)->COLSIM; distinct(COLSIM)->COLSIM; COLSIM$NAME_ES <-replace_na(COLSIM$NAME_ES, "NA")
COLSLE <-read.csv("COLSLE.csv", header=TRUE, fileEncoding= "UTF-8"); select(COLSLE, target_taxon_name, NAME_ES)->COLSLE; distinct(COLSLE)->COLSLE; COLSLE$NAME_ES <-replace_na(COLSLE$NAME_ES, "NA")
COLSPH <-read.csv("COLSPH.csv", header=TRUE, fileEncoding= "UTF-8"); select(COLSPH, target_taxon_name, NAME_ES)->COLSPH; distinct(COLSPH)->COLSPH; COLSPH$NAME_ES <-replace_na(COLSPH$NAME_ES, "NA")
DIAAUS <-read.csv("DIAAUS.csv", header=TRUE, fileEncoding= "UTF-8"); select(DIAAUS, target_taxon_name, NAME_ES)->DIAAUS; distinct(DIAAUS)->DIAAUS; DIAAUS$NAME_ES <-replace_na(DIAAUS$NAME_ES, "NA")
DIACUR <-read.csv("DIACUR.csv", header=TRUE, fileEncoding= "UTF-8"); select(DIACUR, target_taxon_name, NAME_ES)->DIACUR; distinct(DIACUR)->DIACUR; DIACUR$NAME_ES <-replace_na(DIACUR$NAME_ES, "NA")
DIADIM <-read.csv("DIADIM.csv", header=TRUE, fileEncoding= "UTF-8"); select(DIADIM, target_taxon_name, NAME_ES)->DIADIM; distinct(DIADIM)->DIADIM; DIADIM$NAME_ES <-replace_na(DIADIM$NAME_ES, "NA")
DIAPUD <-read.csv("DIAPUD.csv", header=TRUE, fileEncoding= "UTF-8"); select(DIAPUD, target_taxon_name, NAME_ES)->DIAPUD; distinct(DIAPUD)->DIAPUD; DIAPUD$NAME_ES <-replace_na(DIAPUD$NAME_ES, "NA")
DIARIN <-read.csv("DIARIN.csv", header=TRUE, fileEncoding= "UTF-8"); select(DIARIN, target_taxon_name, NAME_ES)->DIARIN; distinct(DIARIN)->DIARIN; DIARIN$NAME_ES <-replace_na(DIARIN$NAME_ES, "NA")
DIASUB <-read.csv("DIASUB.csv", header=TRUE, fileEncoding= "UTF-8"); select(DIASUB, target_taxon_name, NAME_ES)->DIASUB; distinct(DIASUB)->DIASUB; DIASUB$NAME_ES <-replace_na(DIASUB$NAME_ES, "NA")
EPEBIF <-read.csv("EPEBIF.csv", header=TRUE, fileEncoding= "UTF-8"); select(EPEBIF, target_taxon_name, NAME_ES)->EPEBIF; distinct(EPEBIF)->EPEBIF; EPEBIF$NAME_ES <-replace_na(EPEBIF$NAME_ES, "NA")
EPECOM <-read.csv("EPECOM.csv", header=TRUE, fileEncoding= "UTF-8"); select(EPECOM, target_taxon_name, NAME_ES)->EPECOM; distinct(EPECOM)->EPECOM; EPECOM$NAME_ES <-replace_na(EPECOM$NAME_ES, "NA")
EPEMIN <-read.csv("EPEMIN.csv", header=TRUE, fileEncoding= "UTF-8"); select(EPEMIN, target_taxon_name, NAME_ES)->EPEMIN; distinct(EPEMIN)->EPEMIN; EPEMIN$NAME_ES <-replace_na(EPEMIN$NAME_ES, "NA")
EPEPUS <-read.csv("EPEPUS.csv", header=TRUE, fileEncoding= "UTF-8"); select(EPEPUS, target_taxon_name, NAME_ES)->EPEPUS; distinct(EPEPUS)->EPEPUS; EPEPUS$NAME_ES <-replace_na(EPEPUS$NAME_ES, "NA")
EPESCU <-read.csv("EPESCU.csv", header=TRUE, fileEncoding= "UTF-8"); select(EPESCU, target_taxon_name, NAME_ES)->EPESCU; distinct(EPESCU)->EPESCU; EPESCU$NAME_ES <-replace_na(EPESCU$NAME_ES, "NA")
EUCEDW <-read.csv("EUCEDW.csv", header=TRUE, fileEncoding= "UTF-8"); select(EUCEDW, target_taxon_name, NAME_ES)->EUCEDW; distinct(EUCEDW)->EUCEDW; EUCEDW$NAME_ES <-replace_na(EUCEDW$NAME_ES, "NA")
HABCIN <-read.csv("HABCIN.csv", header=TRUE, fileEncoding= "UTF-8"); select(HABCIN, target_taxon_name, NAME_ES)->HABCIN; distinct(HABCIN)->HABCIN; HABCIN$NAME_ES <-replace_na(HABCIN$NAME_ES, "NA")
HALFAR <-read.csv("HALFAR.csv", header=TRUE, fileEncoding= "UTF-8"); select(HALFAR, target_taxon_name, NAME_ES)->HALFAR; distinct(HALFAR)->HALFAR; HALFAR$NAME_ES <-replace_na(HALFAR$NAME_ES, "NA")
HALLIG <-read.csv("HALLIG.csv", header=TRUE, fileEncoding= "UTF-8"); select(HALLIG, target_taxon_name, NAME_ES)->HALLIG; distinct(HALLIG)->HALLIG; HALLIG$NAME_ES <-replace_na(HALLIG$NAME_ES, "NA")
HALTRI <-read.csv("HALTRI.csv", header=TRUE, fileEncoding= "UTF-8"); select(HALTRI, target_taxon_name, NAME_ES)->HALTRI; distinct(HALTRI)->HALTRI; HALTRI$NAME_ES <-replace_na(HALTRI$NAME_ES, "NA")
HERCAR <-read.csv("HERCAR.csv", header=TRUE, fileEncoding= "UTF-8"); select(HERCAR, target_taxon_name, NAME_ES)->HERCAR; distinct(HERCAR)->HERCAR; HERCAR$NAME_ES <-replace_na(HERCAR$NAME_ES, "NA")
HERVAR <-read.csv("HERVAR.csv", header=TRUE, fileEncoding= "UTF-8"); select(HERVAR, target_taxon_name, NAME_ES)->HERVAR; distinct(HERVAR)->HERVAR; HERVAR$NAME_ES <-replace_na(HERVAR$NAME_ES, "NA")
HOLCAL <-read.csv("HOLCAL.csv", header=TRUE, fileEncoding= "UTF-8"); select(HOLCAL, target_taxon_name, NAME_ES)->HOLCAL; distinct(HOLCAL)->HOLCAL; HOLCAL$NAME_ES <-replace_na(HOLCAL$NAME_ES, "NA")
HOPALB <-read.csv("HOPALB.csv", header=TRUE, fileEncoding= "UTF-8"); select(HOPALB, target_taxon_name, NAME_ES)->HOPALB; distinct(HOPALB)->HOPALB; HOPALB$NAME_ES <-replace_na(HOPALB$NAME_ES, "NA")
HOPFUL <-read.csv("HOPFUL.csv", header=TRUE, fileEncoding= "UTF-8"); select(HOPFUL, target_taxon_name, NAME_ES)->HOPFUL; distinct(HOPFUL)->HOPFUL; HOPFUL$NAME_ES <-replace_na(HOPFUL$NAME_ES, "NA")
HOPGRI <-read.csv("HOPGRI.csv", header=TRUE, fileEncoding= "UTF-8"); select(HOPGRI, target_taxon_name, NAME_ES)->HOPGRI; distinct(HOPGRI)->HOPGRI; HOPGRI$NAME_ES <-replace_na(HOPGRI$NAME_ES, "NA")
HOPPRO <-read.csv("HOPPRO.csv", header=TRUE, fileEncoding= "UTF-8"); select(HOPPRO, target_taxon_name, NAME_ES)->HOPPRO; distinct(HOPPRO)->HOPPRO; HOPPRO$NAME_ES <-replace_na(HOPPRO$NAME_ES, "NA")
HYLMES <-read.csv("HYLMES.csv", header=TRUE, fileEncoding= "UTF-8"); select(HYLMES, target_taxon_name, NAME_ES)->HYLMES; distinct(HYLMES)->HYLMES; HYLMES$NAME_ES <-replace_na(HYLMES$NAME_ES, "NA")
HYLMOD <-read.csv("HYLMOD.csv", header=TRUE, fileEncoding= "UTF-8"); select(HYLMOD, target_taxon_name, NAME_ES)->HYLMOD; distinct(HYLMOD)->HYLMOD; HYLMOD$NAME_ES <-replace_na(HYLMOD$NAME_ES, "NA")
HYLWOO <-read.csv("HYLWOO.csv", header=TRUE, fileEncoding= "UTF-8"); select(HYLWOO, target_taxon_name, NAME_ES)->HYLWOO; distinct(HYLWOO)->HYLWOO; HYLWOO$NAME_ES <-replace_na(HYLWOO$NAME_ES, "NA")
LASEGR <-read.csv("LASEGR.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASEGR, target_taxon_name, NAME_ES)->LASEGR; distinct(LASEGR)->LASEGR; LASEGR$NAME_ES <-replace_na(LASEGR$NAME_ES, "NA")
LASELI <-read.csv("LASELI.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASELI, target_taxon_name, NAME_ES)->LASELI; distinct(LASELI)->LASELI; LASELI$NAME_ES <-replace_na(LASELI$NAME_ES, "NA")
LASHDS <-read.csv("LASHDS.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASHDS, target_taxon_name, NAME_ES)->LASHDS; distinct(LASHDS)->LASHDS; LASHDS$NAME_ES <-replace_na(LASHDS$NAME_ES, "NA")
LASICP <-read.csv("LASICP.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASICP, target_taxon_name, NAME_ES)->LASICP; distinct(LASICP)->LASICP; LASICP$NAME_ES <-replace_na(LASICP$NAME_ES, "NA")
LASIMI <-read.csv("LASIMI.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASIMI, target_taxon_name, NAME_ES)->LASIMI; distinct(LASIMI)->LASIMI; LASIMI$NAME_ES <-replace_na(LASIMI$NAME_ES, "NA")
LASLSR <-read.csv("LASLSR.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASLSR, target_taxon_name, NAME_ES)->LASLSR; distinct(LASLSR)->LASLSR; LASLSR$NAME_ES <-replace_na(LASLSR$NAME_ES, "NA")
LASOBZ <-read.csv("LASOBZ.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASOBZ, target_taxon_name, NAME_ES)->LASOBZ; distinct(LASOBZ)->LASOBZ; LASOBZ$NAME_ES <-replace_na(LASOBZ$NAME_ES, "NA")
LASOCC <-read.csv("LASOCC.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASOCC, target_taxon_name, NAME_ES)->LASOCC; distinct(LASOCC)->LASOCC; LASOCC$NAME_ES <-replace_na(LASOCC$NAME_ES, "NA")
LASPCT <-read.csv("LASPCT.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASPCT, target_taxon_name, NAME_ES)->LASPCT; distinct(LASPCT)->LASPCT; LASPCT$NAME_ES <-replace_na(LASPCT$NAME_ES, "NA")
LASPEC <-read.csv("LASPEC.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASPEC, target_taxon_name, NAME_ES)->LASPEC; distinct(LASPEC)->LASPEC; LASPEC$NAME_ES <-replace_na(LASPEC$NAME_ES, "NA")
LASPEX <-read.csv("LASPEX.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASPEX, target_taxon_name, NAME_ES)->LASPEX; distinct(LASPEX)->LASPEX; LASPEX$NAME_ES <-replace_na(LASPEX$NAME_ES, "NA")
#LASPRN <-read.csv("LASPRN.csv", header=TRUE, fileEncoding= "UTF-8")
LASRUI <-read.csv("LASRUI.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASRUI, target_taxon_name, NAME_ES)->LASRUI; distinct(LASRUI)->LASRUI; LASRUI$NAME_ES <-replace_na(LASRUI$NAME_ES, "NA")
LASSCL <-read.csv("LASSCL.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASSCL, target_taxon_name, NAME_ES)->LASSCL; distinct(LASSCL)->LASSCL; LASSCL$NAME_ES <-replace_na(LASSCL$NAME_ES, "NA")
LASSIS <-read.csv("LASSIS.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASSIS, target_taxon_name, NAME_ES)->LASSIS; distinct(LASSIS)->LASSIS; LASSIS$NAME_ES <-replace_na(LASSIS$NAME_ES, "NA")
LASTGU <-read.csv("LASTGU.csv", header=TRUE, fileEncoding= "UTF-8"); select(LASTGU, target_taxon_name, NAME_ES)->LASTGU; distinct(LASTGU)->LASTGU; LASTGU$NAME_ES <-replace_na(LASTGU$NAME_ES, "NA")
MEGANG <-read.csv("MEGANG.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGANG, target_taxon_name, NAME_ES)->MEGANG; distinct(MEGANG)->MEGANG; MEGANG$NAME_ES <-replace_na(MEGANG$NAME_ES, "NA")
MEGAPI <-read.csv("MEGAPI.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGAPI, target_taxon_name, NAME_ES)->MEGAPI; distinct(MEGAPI)->MEGAPI; MEGAPI$NAME_ES <-replace_na(MEGAPI$NAME_ES, "NA")
MEGBRV <-read.csv("MEGBRV.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGBRV, target_taxon_name, NAME_ES)->MEGBRV; distinct(MEGBRV)->MEGBRV; MEGBRV$NAME_ES <-replace_na(MEGBRV$NAME_ES, "NA")
MEGCOQ <-read.csv("MEGCOQ.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGCOQ, target_taxon_name, NAME_ES)->MEGCOQ; distinct(MEGCOQ)->MEGCOQ; MEGCOQ$NAME_ES <-replace_na(MEGCOQ$NAME_ES, "NA")
MEGFID <-read.csv("MEGFID.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGFID, target_taxon_name, NAME_ES)->MEGFID; distinct(MEGFID)->MEGFID; MEGFID$NAME_ES <-replace_na(MEGFID$NAME_ES, "NA")
MEGINI <-read.csv("MEGINI.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGINI, target_taxon_name, NAME_ES)->MEGINI; distinct(MEGINI)->MEGINI; MEGINI$NAME_ES <-replace_na(MEGINI$NAME_ES, "NA")
MEGLIP <-read.csv("MEGLIP.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGLIP, target_taxon_name, NAME_ES)->MEGLIP; distinct(MEGLIP)->MEGLIP; MEGLIP$NAME_ES <-replace_na(MEGLIP$NAME_ES, "NA")
MEGMEN <-read.csv("MEGMEN.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGMEN, target_taxon_name, NAME_ES)->MEGMEN; distinct(MEGMEN)->MEGMEN; MEGMEN$NAME_ES <-replace_na(MEGMEN$NAME_ES, "NA")
MEGMTV <-read.csv("MEGMTV.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGMTV, target_taxon_name, NAME_ES)->MEGMTV; distinct(MEGMTV)->MEGMTV; MEGMTV$NAME_ES <-replace_na(MEGMTV$NAME_ES, "NA")
MEGONO <-read.csv("MEGONO", header=TRUE, fileEncoding= "UTF-8"); select(MEGONO, target_taxon_name, NAME_ES)->MEGONO; distinct(MEGONO)->MEGONO; MEGONO$NAME_ES <-replace_na(MEGONO$NAME_ES, "NA")
MEGPAR <-read.csv("MEGPAR.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGPAR, target_taxon_name, NAME_ES)->MEGPAR; distinct(MEGPAR)->MEGPAR; MEGPAR$NAME_ES <-replace_na(MEGPAR$NAME_ES, "NA")
MEGPHT <-read.csv("MEGPHT.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGPHT, target_taxon_name, NAME_ES)->MEGPHT; distinct(MEGPHT)->MEGPHT; MEGPHT$NAME_ES <-replace_na(MEGPHT$NAME_ES, "NA")
MEGPOL <-read.csv("MEGPOL.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGPOL, target_taxon_name, NAME_ES)->MEGPOL; distinct(MEGPOL)->MEGPOL; MEGPOL$NAME_ES <-replace_na(MEGPOL$NAME_ES, "NA")
MEGPRU <-read.csv("MEGPRU.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGPRU, target_taxon_name, NAME_ES)->MEGPRU; distinct(MEGPRU)->MEGPRU; MEGPRU$NAME_ES <-replace_na(MEGPRU$NAME_ES, "NA")
MEGPUG <-read.csv("MEGPUG.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGPUG, target_taxon_name, NAME_ES)->MEGPUG; distinct(MEGPUG)->MEGPUG; MEGPUG$NAME_ES <-replace_na(MEGPUG$NAME_ES, "NA")
MEGROT <-read.csv("MEGROT.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGROT, target_taxon_name, NAME_ES)->MEGROT; distinct(MEGROT)->MEGROT; MEGROT$NAME_ES <-replace_na(MEGROT$NAME_ES, "NA")
MEGSBN <-read.csv("MEGSBN.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGSBN, target_taxon_name, NAME_ES)->MEGSBN; distinct(MEGSBN)->MEGSBN; MEGSBN$NAME_ES <-replace_na(MEGSBN$NAME_ES, "NA")
MEGTXN <-read.csv("MEGTXN.csv", header=TRUE, fileEncoding= "UTF-8"); select(MEGTXN, target_taxon_name, NAME_ES)->MEGTXN; distinct(MEGTXN)->MEGTXN; MEGTXN$NAME_ES <-replace_na(MEGTXN$NAME_ES, "NA")
MELAGI <-read.csv("MELAGI.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELAGI, target_taxon_name, NAME_ES)->MELAGI; distinct(MELAGI)->MELAGI; MELAGI$NAME_ES <-replace_na(MELAGI$NAME_ES, "NA")
MELBIM <-read.csv("MELBIM.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELBIM, target_taxon_name, NAME_ES)->MELBIM; distinct(MELBIM)->MELBIM; MELBIM$NAME_ES <-replace_na(MELBIM$NAME_ES, "NA")
MELBIW <-read.csv("MELBIW.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELBIW, target_taxon_name, NAME_ES)->MELBIW; distinct(MELBIW)->MELBIW; MELBIW$NAME_ES <-replace_na(MELBIW$NAME_ES, "NA")
MELCMN <-read.csv("MELCMN.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELCMN, target_taxon_name, NAME_ES)->MELCMN; distinct(MELCMN)->MELCMN; MELCMN$NAME_ES <-replace_na(MELCMN$NAME_ES, "NA")
MELCON <-read.csv("MELCON.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELCON, target_taxon_name, NAME_ES)->MELCON; distinct(MELCON)->MELCON; MELCON$NAME_ES <-replace_na(MELCON$NAME_ES, "NA")
MELDRU <-read.csv("MELDRU.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELDRU, target_taxon_name, NAME_ES)->MELDRU; distinct(MELDRU)->MELDRU; MELDRU$NAME_ES <-replace_na(MELDRU$NAME_ES, "NA")
MELLUP <-read.csv("MELLUP.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELLUP, target_taxon_name, NAME_ES)->MELLUP; distinct(MELLUP)->MELLUP; MELLUP$NAME_ES <-replace_na(MELLUP$NAME_ES, "NA")
MELMEN <-read.csv("MELMEN.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELMEN, target_taxon_name, NAME_ES)->MELMEN; distinct(MELMEN)->MELMEN; MELMEN$NAME_ES <-replace_na(MELMEN$NAME_ES, "NA")
MELPAL <-read.csv("MELPAL.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELPAL, target_taxon_name, NAME_ES)->MELPAL; distinct(MELPAL)->MELPAL; MELPAL$NAME_ES <-replace_na(MELPAL$NAME_ES, "NA")
MELRIV <-read.csv("MELRIV.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELRIV, target_taxon_name, NAME_ES)->MELRIV; distinct(MELRIV)->MELRIV; MELRIV$NAME_ES <-replace_na(MELRIV$NAME_ES, "NA")
MELSUB <-read.csv("MELSUB.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELSUB, target_taxon_name, NAME_ES)->MELSUB; distinct(MELSUB)->MELSUB; MELSUB$NAME_ES <-replace_na(MELSUB$NAME_ES, "NA")
MELTND <-read.csv("MELTND.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELTND, target_taxon_name, NAME_ES)->MELTND; distinct(MELTND)->MELTND; MELTND$NAME_ES <-replace_na(MELTND$NAME_ES, "NA")
MELVER <-read.csv("MELVER.csv", header=TRUE, fileEncoding= "UTF-8"); select(MELVER, target_taxon_name, NAME_ES)->MELVER; distinct(MELVER)->MELVER; MELVER$NAME_ES <-replace_na(MELVER$NAME_ES, "NA")
NOMTEX <-read.csv("NOMTEX.csv", header=TRUE, fileEncoding= "UTF-8"); select(NOMTEX, target_taxon_name, NAME_ES)->NOMTEX; distinct(NOMTEX)->NOMTEX; NOMTEX$NAME_ES <-replace_na(NOMTEX$NAME_ES, "NA")
OSMALO <-read.csv("OSMALO.csv", header=TRUE, fileEncoding= "UTF-8"); select(OSMALO, target_taxon_name, NAME_ES)->OSMALO; distinct(OSMALO)->OSMALO; OSMALO$NAME_ES <-replace_na(OSMALO$NAME_ES, "NA")
OSMCAL <-read.csv("OSMCAL.csv", header=TRUE, fileEncoding= "UTF-8"); select(OSMCAL, target_taxon_name, NAME_ES)->OSMCAL; distinct(OSMCAL)->OSMCAL; OSMCAL$NAME_ES <-replace_na(OSMCAL$NAME_ES, "NA")
OSMCLL <-read.csv("OSMCLL.csv", header=TRUE, fileEncoding= "UTF-8"); select(OSMCLL, target_taxon_name, NAME_ES)->OSMCLL; distinct(OSMCLL)->OSMCLL; OSMCLL$NAME_ES <-replace_na(OSMCLL$NAME_ES, "NA")
OSMCOL <-read.csv("OSMCOL.csv", header=TRUE, fileEncoding= "UTF-8"); select(OSMCOL, target_taxon_name, NAME_ES)->OSMCOL; distinct(OSMCOL)->OSMCOL; OSMCOL$NAME_ES <-replace_na(OSMCOL$NAME_ES, "NA")
OSMDEN <-read.csv("OSMDEN.csv", header=TRUE, fileEncoding= "UTF-8"); select(OSMDEN, target_taxon_name, NAME_ES)->OSMDEN; distinct(OSMDEN)->OSMDEN; OSMDEN$NAME_ES <-replace_na(OSMDEN$NAME_ES, "NA")
OSMGEO <-read.csv("OSMGEO.csv", header=TRUE, fileEncoding= "UTF-8"); select(OSMGEO, target_taxon_name, NAME_ES)->OSMGEO; distinct(OSMGEO)->OSMGEO; OSMGEO$NAME_ES <-replace_na(OSMGEO$NAME_ES, "NA")
OSMLIG <-read.csv("OSMLIG.csv", header=TRUE, fileEncoding= "UTF-8"); select(OSMLIG, target_taxon_name, NAME_ES)->OSMLIG; distinct(OSMLIG)->OSMLIG; OSMLIG$NAME_ES <-replace_na(OSMLIG$NAME_ES, "NA")
OSMPUM <-read.csv("OSMPUM.csv", header=TRUE, fileEncoding= "UTF-8"); select(OSMPUM, target_taxon_name, NAME_ES)->OSMPUM; distinct(OSMPUM)->OSMPUM; OSMPUM$NAME_ES <-replace_na(OSMPUM$NAME_ES, "NA")
#OSMRAR <-read.csv("OSMRAR.csv", header=TRUE, fileEncoding= "UTF-8")
OSMTEX <-read.csv("OSMTEX.csv", header=TRUE, fileEncoding= "UTF-8"); select(OSMTEX, target_taxon_name, NAME_ES)->OSMTEX; distinct(OSMTEX)->OSMTEX; OSMTEX$NAME_ES <-replace_na(OSMTEX$NAME_ES, "NA")
PEPPRU <-read.csv("PEPPRU.csv", header=TRUE, fileEncoding= "UTF-8"); select(PEPPRU, target_taxon_name, NAME_ES)->PEPPRU; distinct(PEPPRU)->PEPPRU; PEPPRU$NAME_ES <-replace_na(PEPPRU$NAME_ES, "NA")
PERALB <-read.csv("PERALB.csv", header=TRUE, fileEncoding= "UTF-8"); select(PERALB, target_taxon_name, NAME_ES)->PERALB; distinct(PERALB)->PERALB; PERALB$NAME_ES <-replace_na(PERALB$NAME_ES, "NA")
PROGRS <-read.csv("PROGRS.csv", header=TRUE, fileEncoding= "UTF-8"); select(PROGRS, target_taxon_name, NAME_ES)->PROGRS; distinct(PROGRS)->PROGRS; PROGRS$NAME_ES <-replace_na(PROGRS$NAME_ES, "NA")
PSEAET <-read.csv("PSEAET.csv", header=TRUE, fileEncoding= "UTF-8"); select(PSEAET, target_taxon_name, NAME_ES)->PSEAET; distinct(PSEAET)->PSEAET; PSEAET$NAME_ES <-replace_na(PSEAET$NAME_ES, "NA")
PSEALB <-read.csv("PSEALB.csv", header=TRUE, fileEncoding= "UTF-8"); select(PSEALB, target_taxon_name, NAME_ES)->PSEALB; distinct(PSEALB)->PSEALB; PSEALB$NAME_ES <-replace_na(PSEALB$NAME_ES, "NA")
SPHHER <-read.csv("SPHHER.csv", header=TRUE, fileEncoding= "UTF-8"); select(SPHHER, target_taxon_name, NAME_ES)->SPHHER; distinct(SPHHER)->SPHHER; SPHHER$NAME_ES <-replace_na(SPHHER$NAME_ES, "NA")
STEMON <-read.csv("STEMON.csv", header=TRUE, fileEncoding= "UTF-8"); select(STEMON, target_taxon_name, NAME_ES)->STEMON; distinct(STEMON)->STEMON; STEMON$NAME_ES <-replace_na(STEMON$NAME_ES, "NA")
TRIHEL <-read.csv("TRIHEL.csv", header=TRUE, fileEncoding= "UTF-8"); select(TRIHEL, target_taxon_name, NAME_ES)->TRIHEL; distinct(TRIHEL)->TRIHEL; TRIHEL$NAME_ES <-replace_na(TRIHEL$NAME_ES, "NA")
TRILUN <-read.csv("TRILUN.csv", header=TRUE, fileEncoding= "UTF-8"); select(TRILUN, target_taxon_name, NAME_ES)->TRILUN; distinct(TRILUN)->TRILUN; TRILUN$NAME_ES <-replace_na(TRILUN$NAME_ES, "NA")
TRIREM <-read.csv("TRIREM.csv", header=TRUE, fileEncoding= "UTF-8"); select(TRIREM, target_taxon_name, NAME_ES)->TRIREM; distinct(TRIREM)->TRIREM; TRIREM$NAME_ES <-replace_na(TRIREM$NAME_ES, "NA")
XERCAL <-read.csv("XERCAL.csv", header=TRUE, fileEncoding= "UTF-8"); select(XERCAL, target_taxon_name, NAME_ES)->XERCAL; distinct(XERCAL)->XERCAL; XERCAL$NAME_ES <-replace_na(XERCAL$NAME_ES, "NA")
XERCAZ <-read.csv("XERCAZ.csv", header=TRUE, fileEncoding= "UTF-8"); select(XERCAZ, target_taxon_name, NAME_ES)->XERCAZ; distinct(XERCAZ)->XERCAZ; XERCAZ$NAME_ES <-replace_na(XERCAZ$NAME_ES, "NA")
XYLVAR <-read.csv("XYLVAR.csv", header=TRUE, fileEncoding= "UTF-8"); select(XYLVAR, target_taxon_name, NAME_ES)->XYLVAR; distinct(XYLVAR)->XYLVAR; XYLVAR$NAME_ES <-replace_na(XYLVAR$NAME_ES, "NA")


#Generar lista de las bases de datos#
AA<-list(AGAANG, AGAFEM, AGAOBL, AGASPL, AGATEX, AGAVIR, ANDARC, ANDCAN, ANDCAR, ANDCER, ANDMAN, ANDMIS, ANDNAS, ANDNUB, ANDPRU, ANTBOM, ANTEDW, ANTMAC, ANTMOR, ANTNOT, ANTOCC, ANTPRT, ANTROB, ANTSQU, ANTTEN, ANTURB, ANTURS, ANTUTA, ASHBUC, ASHCAC, ASHCAL, ATOCOP, AUCAUR, AUGMET, AUGPUR, BOMCAL, BOMFER, BOMGRI, BOMHUN, BOMIMP, BOMINS, BOMMIX, BOMMLP, BOMNEV, BOMPEN, BOMRUF, BOMSON, BOMVOS, CALAND, CERACA, CERNAN, CERNAU, CERNEO, COEOCT, COEPOR, COERUF, COESAY, COESOD, COLCOM, COLKIN, COLLTZ, COLSIM, COLSLE, COLSPH, DIAAUS, DIACUR, DIADIM, DIAPUD, DIARIN, DIASUB, EPEBIF, EPECOM, EPEMIN, EPEPUS, EPESCU, EUCEDW, HABCIN, HALFAR, HALLIG, HALTRI, HERCAR, HERVAR, HOLCAL, HOPALB, HOPFUL, HOPGRI, HOPPRO, HYLMES, HYLMOD, HYLWOO, LASEGR, LASELI, LASHDS, LASICP, LASIMI, LASLSR, LASOBZ, LASOCC, LASPCT, LASPEC, LASPEX, LASRUI, LASSCL, LASSIS, LASTGU, MEGANG, MEGAPI, MEGBRV, MEGCOQ, MEGFID, MEGINI, MEGLIP, MEGMEN, MEGMTV, MEGPAR, MEGPHT, MEGPOL, MEGPRU, MEGPUG, MEGROT, MEGSBN, MEGTXN, MELAGI, MELBIM, MELBIW, MELCMN, MELCON, MELDRU, MELLUP, MELMEN, MELPAL, MELRIV, MELSUB, MELTND, MELVER, NOMTEX, OSMALO, OSMCAL, OSMCLL, OSMCOL, OSMDEN, OSMGEO, OSMLIG, OSMPUM, OSMTEX, PEPPRU, PERALB, PROGRS, PSEAET, PSEALB, SPHHER, STEMON, TRIHEL, TRILUN, TRIREM, XERCAL, XERCAZ, XYLVAR)
View(AA)

#Unir las listas en un solo data frame#
LISTA<-Reduce(function(x, y) merge(x, y, all=TRUE), AA)

#Eliminar registros duplicados#
LISTA2 <-distinct(LISTA)

#Unir los países por planta#
LISTA3 <-aggregate(NAME_ES ~ target_taxon_name , data=LISTA2, FUN=paste, collapse='|')

#Eliminar registros repetidos#
LISTA4 <-distinct(LISTA3)
View(LISTA3)

#Escribir archivo
write.csv(LISTA4, "listado_paises.csv", fileEncoding = "UTF-8")
